apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: urlshortener
  labels:
    app: urlshortener
spec:
  selector:
    matchLabels:
      app: urlshortener
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: urlshortener
    spec:
      containers:
        - name: urlshortener
          image: eu.gcr.io/cognitedata/urlshortener:latest
          ports:
            - containerPort: 3000
